= Definitions
:navtitle:definitions

Based on definitions from IEEE
https://pascal.computer.org/[SEVOCAB]

[unordered]
Context:: immediate environment in which a function (or set of functions in a diagram) operates

module:: module. (1) program unit that is discrete and identifiable with respect to compiling, combining with other units, and loading (ISO/IEC 19506:2012 Information technology -- Object Management Group Architecture-Driven Modernization (ADM) -- Knowledge Discovery Meta-Model (KDM), 4) (2) logically separable part of a program (ISO/IEC 19506:2012 Information technology -- Object Management Group Architecture-Driven Modernization (ADM) -- Knowledge Discovery Meta-Model (KDM), 4) (3) set of source code files under version control that can be manipulated together as one (ISO/IEC/IEEE 24765:2017 Systems and software engineering-Vocabulary) (4) collection of both data and the routines that act on it (ISO/IEC/IEEE 24765:2017 Systems and software engineering-Vocabulary) Note: The terms 'module', 'component,' and 'unit' are often used interchangeably or defined to be subelements of one another in different ways depending upon the context. The relationship of these terms is not yet standardized.

Date Format::
    explicitly state the month and day using words rather than just numerals (e.g. "October 31, 2023" or Oct 31, 2023 --less formal).


Modelling::
    referring to mathematics equation or plot diagram. e.g. f(x) = 1/x

Simulation::
    referring to executable runtime program, e.g. kotlin app.
