/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package project.kt.app.app

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class MessageUtilsTest {
    @Test
    fun testGetMessage() {
        assertEquals("Hello      World!", MessageUtils.getMessage())
    }

    @Test
    fun testSum() {
        assertEquals(3, MessageUtils.sum(1, 2))
    }
}
