/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package project.kt.app.app

import project.kt.app.utilities.StringUtils

import org.apache.commons.text.WordUtils

fun main() {
    val tokens = StringUtils.split(MessageUtils.getMessage())
    val result = StringUtils.join(tokens)
    val sum = MessageUtils.sum(1,2)
    println(WordUtils.capitalize(result)+sum)

}
