= Vega Template
:navtitle: diagramming
:toc:
:icons: font

== Tips
https://vega.github.io/vega/examples/[vega example]

== Excelidraw
[excalidraw]
....
{
  "type": "excalidraw",
  "version": 2,
  "source": "https://excalidraw.com",
  "elements": [
    {
      "type": "line",
      "version": 2667,
      "versionNonce": 1541327723,
      "isDeleted": false,
      "id": "WuX9NZ6pVbGQ_UD19cOu0",
      "fillStyle": "solid",
      "strokeWidth": 1,
      "strokeStyle": "solid",
      "roughness": 1,
      "opacity": 100,
      "angle": 4.711993274549773,
      "x": 617.6179750876985,
      "y": 1545.9125732998982,
      "strokeColor": "#000000",
      "backgroundColor": "transparent",
      "width": 129.2437670405741,
      "height": 149.23780926294657,
      "seed": 737226251,
      "groupIds": [
        "JqtATRP7r__vucbJGPG6e",
        "dehxwSE8omFP0Tmmff-w-"
      ],
      "roundness": null,
      "boundElements": [],
      "updated": 1682938547543,
      "link": null,
      "locked": false,
      "lastCommittedPoint": null,
      "startArrowhead": null,
      "endArrowhead": null,
      "points": [
        [
          0,
          0
        ],
        [
          64.62188352028706,
          37.30945231573664
        ],
        [
          64.62188352028706,
          111.92835694721012
        ],
        [
          0,
          149.23780926294657
        ],
        [
          -64.62188352028706,
          111.92835694721012
        ],
        [
          -64.62188352028706,
          37.30945231573664
        ],
        [
          0,
          0
        ]
      ]
    },
    {
      "type": "text",
      "version": 2436,
      "versionNonce": 1859531973,
      "isDeleted": false,
      "id": "rD1U1jftPYhU5lEydLvJX",
      "fillStyle": "solid",
      "strokeWidth": 1,
      "strokeStyle": "dotted",
      "roughness": 1,
      "opacity": 100,
      "angle": 0,
      "x": 597.9845926879557,
      "y": 1602.4875532823298,
      "strokeColor": "#000000",
      "backgroundColor": "#fff",
      "width": 42.55467426266707,
      "height": 36.966686733225934,
      "seed": 693449899,
      "groupIds": [
        "JqtATRP7r__vucbJGPG6e",
        "dehxwSE8omFP0Tmmff-w-"
      ],
      "roundness": null,
      "boundElements": [],
      "updated": 1682938547543,
      "link": null,
      "locked": false,
      "fontSize": 14.414072702613986,
      "fontFamily": 1,
      "text": "Use\nCases",
      "textAlign": "center",
      "verticalAlign": "top",
      "containerId": null,
      "originalText": "Use\nCases",
      "lineHeight": 1.282312344883693,
      "baseline": 30.999999999999993
    },
    {
      "type": "ellipse",
      "version": 539,
      "versionNonce": 946349579,
      "isDeleted": false,
      "id": "f76g_YiypL2xyAUgR0n7-",
      "fillStyle": "solid",
      "strokeWidth": 1,
      "strokeStyle": "dashed",
      "roughness": 0,
      "opacity": 100,
      "angle": 0,
      "x": 616.5993063912208,
      "y": 1555.3031361793069,
      "strokeColor": "#000",
      "backgroundColor": "#000",
      "width": 0.6125294022663926,
      "height": 0.6125294022663926,
      "seed": 1975478091,
      "groupIds": [
        "dehxwSE8omFP0Tmmff-w-"
      ],
      "roundness": null,
      "boundElements": [
        {
          "type": "arrow",
          "id": "fmSIgkn4dZWIT0h5s7PDM"
        }
      ],
      "updated": 1682938547543,
      "link": null,
      "locked": false
    },
    {
      "type": "ellipse",
      "version": 534,
      "versionNonce": 2083335339,
      "isDeleted": false,
      "id": "hd6zlfCEwpe9mZlWrMw8C",
      "fillStyle": "solid",
      "strokeWidth": 1,
      "strokeStyle": "dashed",
      "roughness": 0,
      "opacity": 100,
      "angle": 0,
      "x": 616.3335996640928,
      "y": 1684.641140701444,
      "strokeColor": "#000000",
      "backgroundColor": "#000",
      "width": 1.1439428565236363,
      "height": 1.1439428565236363,
      "seed": 663373291,
      "groupIds": [
        "dehxwSE8omFP0Tmmff-w-"
      ],
      "roundness": null,
      "boundElements": [
        {
          "type": "arrow",
          "id": "mlLPTw2r4-f0JH630f3yK"
        }
      ],
      "updated": 1682938547543,
      "link": null,
      "locked": false
    },
    {
      "type": "line",
      "version": 3343,
      "versionNonce": 450387787,
      "isDeleted": false,
      "id": "C1AyQiH2gMbNDE6x41HKR",
      "fillStyle": "solid",
      "strokeWidth": 1,
      "strokeStyle": "solid",
      "roughness": 1,
      "opacity": 100,
      "angle": 4.711993274549773,
      "x": 615.8457830249644,
      "y": 1446.276950382483,
      "strokeColor": "#000000",
      "backgroundColor": "transparent",
      "width": 302.2099141900992,
      "height": 348.96186148083007,
      "seed": 633360523,
      "groupIds": [
        "6Eq9m6f4ugrvETdnjlEUl",
        "XyZ9QfV53Yt5e0IPp7mNp"
      ],
      "roundness": null,
      "boundElements": [],
      "updated": 1682938547543,
      "link": null,
      "locked": false,
      "lastCommittedPoint": null,
      "startArrowhead": null,
      "endArrowhead": null,
      "points": [
        [
          0,
          0
        ],
        [
          151.1049570950496,
          87.24046537020752
        ],
        [
          151.1049570950496,
          261.721396110623
        ],
        [
          0,
          348.96186148083007
        ],
        [
          -151.1049570950496,
          261.721396110623
        ],
        [
          -151.1049570950496,
          87.24046537020752
        ],
        [
          0,
          0
        ]
      ]
    },
    {
      "type": "ellipse",
      "version": 1167,
      "versionNonce": 1691897573,
      "isDeleted": false,
      "id": "JMe5BhSgXrLj4prqzqua9",
      "fillStyle": "solid",
      "strokeWidth": 1,
      "strokeStyle": "dashed",
      "roughness": 0,
      "opacity": 100,
      "angle": 4.711993274549773,
      "x": 615.5298982502619,
      "y": 1469.5081101613694,
      "strokeColor": "#000000",
      "backgroundColor": "#000",
      "width": 0.2506587877554683,
      "height": 0.2506587877554683,
      "seed": 303826731,
      "groupIds": [
        "XyZ9QfV53Yt5e0IPp7mNp"
      ],
      "roundness": null,
      "boundElements": [
        {
          "type": "arrow",
          "id": "fmSIgkn4dZWIT0h5s7PDM"
        }
      ],
      "updated": 1682938547543,
      "link": null,
      "locked": false
    },
    {
      "type": "ellipse",
      "version": 930,
      "versionNonce": 1024928325,
      "isDeleted": false,
      "id": "Qob4AN1R39H2IctgXfKzz",
      "fillStyle": "solid",
      "strokeWidth": 1,
      "strokeStyle": "dashed",
      "roughness": 0,
      "opacity": 100,
      "angle": 4.711993274549773,
      "x": 615.2938630978529,
      "y": 1771.4521122276244,
      "strokeColor": "#000000",
      "backgroundColor": "#000",
      "width": 0.722729092552616,
      "height": 0.722729092552616,
      "seed": 1929898443,
      "groupIds": [
        "XyZ9QfV53Yt5e0IPp7mNp"
      ],
      "roundness": null,
      "boundElements": [
        {
          "type": "arrow",
          "id": "mlLPTw2r4-f0JH630f3yK"
        }
      ],
      "updated": 1682938547543,
      "link": null,
      "locked": false
    },
    {
      "type": "arrow",
      "version": 3402,
      "versionNonce": 61474821,
      "isDeleted": false,
      "id": "fmSIgkn4dZWIT0h5s7PDM",
      "fillStyle": "solid",
      "strokeWidth": 1,
      "strokeStyle": "dashed",
      "roughness": 0,
      "opacity": 100,
      "angle": 0,
      "x": 616.9210277878852,
      "y": 1554.873453281002,
      "strokeColor": "#000000",
      "backgroundColor": "#000",
      "width": 1.2921111107909395,
      "height": 84.68546295560493,
      "seed": 496924779,
      "groupIds": [],
      "roundness": {
        "type": 2
      },
      "boundElements": [],
      "updated": 1682938547564,
      "link": null,
      "locked": false,
      "startBinding": {
        "elementId": "f76g_YiypL2xyAUgR0n7-",
        "focus": 0.08712237223675462,
        "gap": 1
      },
      "endBinding": {
        "elementId": "JMe5BhSgXrLj4prqzqua9",
        "focus": 0.2774139885638178,
        "gap": 1
      },
      "lastCommittedPoint": null,
      "startArrowhead": null,
      "endArrowhead": null,
      "points": [
        [
          0,
          0
        ],
        [
          -1.2921111107909395,
          -84.68546295560493
        ]
      ]
    },
    {
      "type": "arrow",
      "version": 2728,
      "versionNonce": 1200930661,
      "isDeleted": false,
      "id": "mlLPTw2r4-f0JH630f3yK",
      "fillStyle": "solid",
      "strokeWidth": 1,
      "strokeStyle": "dashed",
      "roughness": 0,
      "opacity": 100,
      "angle": 0,
      "x": 616.8531069938077,
      "y": 1686.2135540641282,
      "strokeColor": "#000000",
      "backgroundColor": "#000",
      "width": 1.2486169344460927,
      "height": 84.810341459042,
      "seed": 1604989707,
      "groupIds": [],
      "roundness": {
        "type": 2
      },
      "boundElements": [],
      "updated": 1682938547564,
      "link": null,
      "locked": false,
      "startBinding": {
        "elementId": "hd6zlfCEwpe9mZlWrMw8C",
        "focus": 0.06596665592532178,
        "gap": 1
      },
      "endBinding": {
        "elementId": "Qob4AN1R39H2IctgXfKzz",
        "focus": -0.17255540716062828,
        "gap": 1
      },
      "lastCommittedPoint": null,
      "startArrowhead": null,
      "endArrowhead": null,
      "points": [
        [
          0,
          0
        ],
        [
          -1.2486169344460927,
          84.810341459042
        ]
      ]
    },
    {
      "type": "rectangle",
      "version": 4412,
      "versionNonce": 1907039493,
      "isDeleted": false,
      "id": "nWzsIX2UOYfEeE0iUbN1Q",
      "fillStyle": "solid",
      "strokeWidth": 1,
      "strokeStyle": "solid",
      "roughness": 1,
      "opacity": 100,
      "angle": 0,
      "x": 460.2034663817151,
      "y": 1537.5143639763264,
      "strokeColor": "#000000",
      "backgroundColor": "#fff",
      "width": 48.88612385098828,
      "height": 46.68857618835332,
      "seed": 1772460459,
      "groupIds": [
        "s8OzCx3o07etUkwGvzk9m"
      ],
      "roundness": null,
      "boundElements": [
        {
          "type": "arrow",
          "id": "z752DI4YQp-AJVnrOPj1y"
        }
      ],
      "updated": 1682938547543,
      "link": null,
      "locked": false
    },
    {
      "type": "text",
      "version": 3431,
      "versionNonce": 669311435,
      "isDeleted": false,
      "id": "slfCSV1MJUKoD_rZE5CzI",
      "fillStyle": "solid",
      "strokeWidth": 1,
      "strokeStyle": "solid",
      "roughness": 1,
      "opacity": 100,
      "angle": 0,
      "x": 468.77947977719793,
      "y": 1550.4549103357722,
      "strokeColor": "#000000",
      "backgroundColor": "transparent",
      "width": 31.734097059988095,
      "height": 18.90541952509929,
      "seed": 2025532491,
      "groupIds": [
        "s8OzCx3o07etUkwGvzk9m"
      ],
      "roundness": {
        "type": 2
      },
      "boundElements": [
        {
          "id": "z752DI4YQp-AJVnrOPj1y",
          "type": "arrow"
        }
      ],
      "updated": 1682938547543,
      "link": null,
      "locked": false,
      "fontSize": 8.002878257473016,
      "fontFamily": 1,
      "text": "Primary\nAdapter",
      "textAlign": "center",
      "verticalAlign": "top",
      "containerId": null,
      "originalText": "Primary\nAdapter",
      "lineHeight": 1.1811637586418098,
      "baseline": 16
    },
    {
      "type": "arrow",
      "version": 3657,
      "versionNonce": 1609665221,
      "isDeleted": false,
      "id": "z752DI4YQp-AJVnrOPj1y",
      "fillStyle": "hachure",
      "strokeWidth": 1,
      "strokeStyle": "solid",
      "roughness": 0,
      "opacity": 100,
      "angle": 0,
      "x": 510.08959023270336,
      "y": 1568.964011073459,
      "strokeColor": "#000000",
      "backgroundColor": "transparent",
      "width": 21.82853151629621,
      "height": 7.080900529233531,
      "seed": 1086679787,
      "groupIds": [],
      "roundness": {
        "type": 2
      },
      "boundElements": [],
      "updated": 1682938547564,
      "link": null,
      "locked": false,
      "startBinding": {
        "elementId": "slfCSV1MJUKoD_rZE5CzI",
        "focus": 0.054999617434508485,
        "gap": 9.576013395517379
      },
      "endBinding": {
        "elementId": "BjxuzmxXgQwSHgQJv-NuM",
        "focus": -0.10502686318594535,
        "gap": 11.110577209878784
      },
      "lastCommittedPoint": null,
      "startArrowhead": null,
      "endArrowhead": null,
      "points": [
        [
          0,
          0
        ],
        [
          21.82853151629621,
          7.080900529233531
        ]
      ]
    },
    {
      "type": "rectangle",
      "version": 4444,
      "versionNonce": 376528837,
      "isDeleted": false,
      "id": "LdDGnqOWnabD5mRu0RY-Z",
      "fillStyle": "solid",
      "strokeWidth": 1,
      "strokeStyle": "solid",
      "roughness": 1,
      "opacity": 100,
      "angle": 0,
      "x": 532.5556058570023,
      "y": 1559.83944876943,
      "strokeColor": "#087f5b",
      "backgroundColor": "#fff",
      "width": 48.88612385098828,
      "height": 46.68857618835332,
      "seed": 374265227,
      "groupIds": [
        "bpT3U_F99I-FYBOe3UWb6"
      ],
      "roundness": null,
      "boundElements": [
        {
          "type": "arrow",
          "id": "z752DI4YQp-AJVnrOPj1y"
        }
      ],
      "updated": 1682938547543,
      "link": null,
      "locked": false
    },
    {
      "type": "text",
      "version": 3464,
      "versionNonce": 1269377803,
      "isDeleted": false,
      "id": "BjxuzmxXgQwSHgQJv-NuM",
      "fillStyle": "solid",
      "strokeWidth": 1,
      "strokeStyle": "solid",
      "roughness": 1,
      "opacity": 100,
      "angle": 0,
      "x": 543.0286989588783,
      "y": 1572.7799951288757,
      "strokeColor": "#000000",
      "backgroundColor": "transparent",
      "width": 27.93993764720565,
      "height": 19.772878950330153,
      "seed": 1485958187,
      "groupIds": [
        "bpT3U_F99I-FYBOe3UWb6"
      ],
      "roundness": {
        "type": 2
      },
      "boundElements": [
        {
          "id": "z752DI4YQp-AJVnrOPj1y",
          "type": "arrow"
        }
      ],
      "updated": 1682938547543,
      "link": null,
      "locked": false,
      "fontSize": 8.002878257473016,
      "fontFamily": 1,
      "text": "Primary\nPort",
      "textAlign": "center",
      "verticalAlign": "top",
      "containerId": null,
      "originalText": "Primary\nPort",
      "lineHeight": 1.2353604737062203,
      "baseline": 16
    },
    {
      "type": "rectangle",
      "version": 4625,
      "versionNonce": 1795527083,
      "isDeleted": false,
      "id": "1qEJVbwvmHGkawtkXxlyY",
      "fillStyle": "cross-hatch",
      "strokeWidth": 1,
      "strokeStyle": "solid",
      "roughness": 1,
      "opacity": 100,
      "angle": 0,
      "x": 658.4981518206201,
      "y": 1630.1981794503813,
      "strokeColor": "#000000",
      "backgroundColor": "#fa5252",
      "width": 43.8705912982028,
      "height": 41.8985037655596,
      "seed": 460926667,
      "groupIds": [
        "2gINyC304OmZKdDjWZmgI"
      ],
      "roundness": null,
      "boundElements": [
        {
          "type": "arrow",
          "id": "rAIrvj_UdjBLJHx9i_zfT"
        }
      ],
      "updated": 1682938547543,
      "link": null,
      "locked": false
    },
    {
      "type": "text",
      "version": 3760,
      "versionNonce": 1595273861,
      "isDeleted": false,
      "id": "2Ali0pzAnqOzvwN9kL8G9",
      "fillStyle": "solid",
      "strokeWidth": 1,
      "strokeStyle": "solid",
      "roughness": 1,
      "opacity": 100,
      "angle": 0,
      "x": 660.3743410310467,
      "y": 1673.2888085139202,
      "strokeColor": "#000000",
      "backgroundColor": "transparent",
      "width": 38.68606751151552,
      "height": 19.772878950330153,
      "seed": 295640427,
      "groupIds": [
        "2gINyC304OmZKdDjWZmgI"
      ],
      "roundness": {
        "type": 2
      },
      "boundElements": [
        {
          "id": "rAIrvj_UdjBLJHx9i_zfT",
          "type": "arrow"
        }
      ],
      "updated": 1682938547543,
      "link": null,
      "locked": false,
      "fontSize": 8.002878257473016,
      "fontFamily": 1,
      "text": "Secondary\nPort",
      "textAlign": "center",
      "verticalAlign": "top",
      "containerId": null,
      "originalText": "Secondary\nPort",
      "lineHeight": 1.2353604737062203,
      "baseline": 16
    },
    {
      "type": "arrow",
      "version": 5079,
      "versionNonce": 492694053,
      "isDeleted": false,
      "id": "rAIrvj_UdjBLJHx9i_zfT",
      "fillStyle": "hachure",
      "strokeWidth": 1,
      "strokeStyle": "dashed",
      "roughness": 0,
      "opacity": 100,
      "angle": 0,
      "x": 703.3687431188229,
      "y": 1662.8603879917455,
      "strokeColor": "#000000",
      "backgroundColor": "transparent",
      "width": 23.0278737938595,
      "height": 11.883352115657999,
      "seed": 911095819,
      "groupIds": [],
      "roundness": {
        "type": 2
      },
      "boundElements": [],
      "updated": 1682938547565,
      "link": null,
      "locked": false,
      "startBinding": {
        "elementId": "2Ali0pzAnqOzvwN9kL8G9",
        "focus": -1.6367796230535223,
        "gap": 10.428420522174633
      },
      "endBinding": {
        "elementId": "ZM5gMXflRQMGdudEJ-5V7",
        "focus": 0.020092122566669247,
        "gap": 8.395471914715472
      },
      "lastCommittedPoint": null,
      "startArrowhead": null,
      "endArrowhead": null,
      "points": [
        [
          0,
          0
        ],
        [
          23.0278737938595,
          11.883352115657999
        ]
      ]
    },
    {
      "type": "text",
      "version": 3843,
      "versionNonce": 1955029739,
      "isDeleted": false,
      "id": "9KjDgDVI3ujN6f0RHhh1M",
      "fillStyle": "solid",
      "strokeWidth": 1,
      "strokeStyle": "solid",
      "roughness": 1,
      "opacity": 100,
      "angle": 0,
      "x": 726.250890562129,
      "y": 1709.1194758043478,
      "strokeColor": "#000000",
      "backgroundColor": "transparent",
      "width": 38.68606751151552,
      "height": 19.772878950330153,
      "seed": 931200683,
      "groupIds": [
        "9SWhy9bkw2MvnXjM4QQRi"
      ],
      "roundness": {
        "type": 2
      },
      "boundElements": [],
      "updated": 1682938547543,
      "link": null,
      "locked": false,
      "fontSize": 8.002878257473016,
      "fontFamily": 1,
      "text": "Secondary\nAdapter",
      "textAlign": "center",
      "verticalAlign": "top",
      "containerId": null,
      "originalText": "Secondary\nAdapter",
      "lineHeight": 1.2353604737062203,
      "baseline": 16
    },
    {
      "type": "rectangle",
      "version": 4682,
      "versionNonce": 71619909,
      "isDeleted": false,
      "id": "Ac2U1krjtyMnXUM8a3jzq",
      "fillStyle": "solid",
      "strokeWidth": 1,
      "strokeStyle": "solid",
      "roughness": 1,
      "opacity": 100,
      "angle": 0,
      "x": 726.2677173955136,
      "y": 1664.5845635407654,
      "strokeColor": "#000000",
      "backgroundColor": "#fa5252",
      "width": 43.8705912982028,
      "height": 41.8985037655596,
      "seed": 534901067,
      "groupIds": [
        "jCWJu8NFm7IGDVhLWfcf_",
        "9SWhy9bkw2MvnXjM4QQRi"
      ],
      "roundness": null,
      "boundElements": [
        {
          "type": "arrow",
          "id": "rAIrvj_UdjBLJHx9i_zfT"
        }
      ],
      "updated": 1682938547543,
      "link": null,
      "locked": false
    },
    {
      "type": "text",
      "version": 3836,
      "versionNonce": 1863437707,
      "isDeleted": false,
      "id": "ZM5gMXflRQMGdudEJ-5V7",
      "fillStyle": "solid",
      "strokeWidth": 1,
      "strokeStyle": "solid",
      "roughness": 1,
      "opacity": 100,
      "angle": 0,
      "x": 734.7920888273978,
      "y": 1677.7739345889743,
      "strokeColor": "#fff",
      "backgroundColor": "#4c6ef5",
      "width": 25.600130755644134,
      "height": 16.410340227976974,
      "seed": 1087082475,
      "groupIds": [
        "Q8F0_EfXu68_SLOM1VtFJ",
        "YgquOD-1uoGqgo-1xAHZE",
        "jCWJu8NFm7IGDVhLWfcf_",
        "9SWhy9bkw2MvnXjM4QQRi"
      ],
      "roundness": null,
      "boundElements": [
        {
          "id": "rAIrvj_UdjBLJHx9i_zfT",
          "type": "arrow"
        }
      ],
      "updated": 1682938547543,
      "link": null,
      "locked": false,
      "fontSize": 13.128272182381604,
      "fontFamily": 1,
      "text": "Impl",
      "textAlign": "center",
      "verticalAlign": "middle",
      "containerId": null,
      "originalText": "Impl",
      "lineHeight": 1.2499999999999976,
      "baseline": 11
    }
  ],
  "appState": {
    "gridSize": null,
    "viewBackgroundColor": "#ffffff"
  },
  "files": {}
}
....


== Vega - WordCloud
[vega]
....
{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "width": 800,
  "height": 400,
  "padding": 0,

  "data": [
    {
      "name": "table",
      "values": [
        "Declarative visualization grammars can accelerate development, facilitate retargeting across platforms, and allow language-level optimizations. However, existing declarative visualization languages are primarily concerned with visual encoding, and rely on imperative event handlers for interactive behaviors. In response, we introduce a model of declarative interaction design for data visualizations. Adopting methods from reactive programming, we model low-level events as composable data streams from which we form higher-level semantic signals. Signals feed predicates and scale inversions, which allow us to generalize interactive selections at the level of item geometry (pixels) into interactive queries over the data domain. Production rules then use these queries to manipulate the visualization’s appearance. To facilitate reuse and sharing, these constructs can be encapsulated as named interactors: standalone, purely declarative specifications of interaction techniques. We assess our model’s feasibility and expressivity by instantiating it with extensions to the Vega visualization grammar. Through a diverse range of examples, we demonstrate coverage over an established taxonomy of visualization interaction techniques.",
        "We present Reactive Vega, a system architecture that provides the first robust and comprehensive treatment of declarative visual and interaction design for data visualization. Starting from a single declarative specification, Reactive Vega constructs a dataflow graph in which input data, scene graph elements, and interaction events are all treated as first-class streaming data sources. To support expressive interactive visualizations that may involve time-varying scalar, relational, or hierarchical data, Reactive Vega’s dataflow graph can dynamically re-write itself at runtime by extending or pruning branches in a data-driven fashion. We discuss both compile- and run-time optimizations applied within Reactive Vega, and share the results of benchmark studies that indicate superior interactive performance to both D3 and the original, non-reactive Vega system.",
        "We present Vega-Lite, a high-level grammar that enables rapid specification of interactive data visualizations. Vega-Lite combines a traditional grammar of graphics, providing visual encoding rules and a composition algebra for layered and multi-view displays, with a novel grammar of interaction. Users specify interactive semantics by composing selections. In Vega-Lite, a selection is an abstraction that defines input event processing, points of interest, and a predicate function for inclusion testing. Selections parameterize visual encodings by serving as input data, defining scale extents, or by driving conditional logic. The Vega-Lite compiler automatically synthesizes requisite data flow and event handling logic, which users can override for further customization. In contrast to existing reactive specifications, Vega-Lite selections decompose an interaction design into concise, enumerable semantic units. We evaluate Vega-Lite through a range of examples, demonstrating succinct specification of both customized interaction methods and common techniques such as panning, zooming, and linked selection."
      ],
      "transform": [
        {
          "type": "countpattern",
          "field": "data",
          "case": "upper",
          "pattern": "[\\w']{3,}",
          "stopwords": "(i|me|my|myself|we|us|our|ours|ourselves|you|your|yours|yourself|yourselves|he|him|his|himself|she|her|hers|herself|it|its|itself|they|them|their|theirs|themselves|what|which|who|whom|whose|this|that|these|those|am|is|are|was|were|be|been|being|have|has|had|having|do|does|did|doing|will|would|should|can|could|ought|i'm|you're|he's|she's|it's|we're|they're|i've|you've|we've|they've|i'd|you'd|he'd|she'd|we'd|they'd|i'll|you'll|he'll|she'll|we'll|they'll|isn't|aren't|wasn't|weren't|hasn't|haven't|hadn't|doesn't|don't|didn't|won't|wouldn't|shan't|shouldn't|can't|cannot|couldn't|mustn't|let's|that's|who's|what's|here's|there's|when's|where's|why's|how's|a|an|the|and|but|if|or|because|as|until|while|of|at|by|for|with|about|against|between|into|through|during|before|after|above|below|to|from|up|upon|down|in|out|on|off|over|under|again|further|then|once|here|there|when|where|why|how|all|any|both|each|few|more|most|other|some|such|no|nor|not|only|own|same|so|than|too|very|say|says|said|shall)"
        },
        {
          "type": "formula", "as": "angle",
          "expr": "[-45, 0, 45][~~(random() * 3)]"
        },
        {
          "type": "formula", "as": "weight",
          "expr": "if(datum.text=='VEGA', 600, 300)"
        }
      ]
    }
  ],

  "scales": [
    {
      "name": "color",
      "type": "ordinal",
      "domain": {"data": "table", "field": "text"},
      "range": ["#d5a928", "#652c90", "#939597"]
    }
  ],

  "marks": [
    {
      "type": "text",
      "from": {"data": "table"},
      "encode": {
        "enter": {
          "text": {"field": "text"},
          "align": {"value": "center"},
          "baseline": {"value": "alphabetic"},
          "fill": {"scale": "color", "field": "text"}
        },
        "update": {
          "fillOpacity": {"value": 1}
        },
        "hover": {
          "fillOpacity": {"value": 0.5}
        }
      },
      "transform": [
        {
          "type": "wordcloud",
          "size": [800, 400],
          "text": {"field": "text"},
          "rotate": {"field": "datum.angle"},
          "font": "Helvetica Neue, Arial",
          "fontSize": {"field": "datum.count"},
          "fontWeight": {"field": "datum.weight"},
          "fontSizeRange": [12, 56],
          "padding": 2
        }
      ]
    }
  ]
}
....

== Vega - Divergence Stacked
[vegalite]
....
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "A diverging stacked bar chart for sentiments towards a set of eight questions, displayed as percentages with neutral responses straddling the 0% mark",
  "data": {
    "values": [
      {"question": "Question 1", "type": "Strongly disagree", "value": 24, "percentage": 0.7},
      {"question": "Question 1", "type": "Disagree", "value": 294, "percentage": 9.1},
      {"question": "Question 1", "type": "Neither agree nor disagree", "value": 594, "percentage": 18.5},
      {"question": "Question 1", "type": "Agree", "value": 1927, "percentage": 59.9},
      {"question": "Question 1", "type": "Strongly agree", "value": 376, "percentage": 11.7},
      {"question": "Question 2", "type": "Strongly disagree", "value": 2, "percentage": 18.2},
      {"question": "Question 2", "type": "Disagree", "value": 2, "percentage": 18.2},
      {"question": "Question 2", "type": "Neither agree nor disagree", "value": 0, "percentage": 0},
      {"question": "Question 2", "type": "Agree", "value": 7, "percentage": 63.6},
      {"question": "Question 2", "type": "Strongly agree", "value": 11, "percentage": 0}
    ]
  },
  "transform": [
    {
      "calculate": "if(datum.type === 'Strongly disagree',-2,0) + if(datum.type==='Disagree',-1,0) + if(datum.type =='Neither agree nor disagree',0,0) + if(datum.type ==='Agree',1,0) + if(datum.type ==='Strongly agree',2,0)",
      "as": "q_order"
    },
    {
      "calculate": "if(datum.type === 'Disagree' || datum.type === 'Strongly disagree', datum.percentage,0) + if(datum.type === 'Neither agree nor disagree', datum.percentage / 2,0)",
      "as": "signed_percentage"
    },
    {"stack": "percentage", "as": ["v1", "v2"], "groupby": ["question"]},
    {
      "joinaggregate": [
        {
          "field": "signed_percentage",
          "op": "sum",
          "as": "offset"
        }
      ],
      "groupby": ["question"]
    },
    {"calculate": "datum.v1 - datum.offset", "as": "nx"},
    {"calculate": "datum.v2 - datum.offset", "as": "nx2"}
  ],
  "mark": "bar",
  "encoding": {
    "x": {
      "field": "nx",
      "type": "quantitative",
      "axis": {
        "title": "Percentage"
      }
    },
    "x2": {"field": "nx2"},
    "y": {
      "field": "question",
      "type": "nominal",
      "axis": {
        "title": "Question",
        "offset": 5,
        "ticks": false,
        "minExtent": 60,
        "domain": false
      }
    },
    "color": {
      "field": "type",
      "type": "nominal",
      "legend": {
        "title": "Response"
      },
      "scale": {
        "domain": ["Strongly disagree", "Disagree", "Neither agree nor disagree", "Agree", "Strongly agree"],
        "range": ["#c30d24", "#f3a583", "#cccccc", "#94c6da", "#1770ab"],
        "type": "ordinal"
      }
    }
  }
}
....

== Vega-lite Bubble
[vegalite]
....
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "Horizontally concatenated charts that show different types of discretizing scales.",
  "data": {
    "values": [
      {"a": "A", "b": 28},
      {"a": "B", "b": 55},
      {"a": "C", "b": 43},
      {"a": "D", "b": 91},
      {"a": "E", "b": 81},
      {"a": "F", "b": 53},
      {"a": "G", "b": 19},
      {"a": "H", "b": 87},
      {"a": "I", "b": 52}
    ]
  },
  "hconcat": [
    {
      "mark": "circle",
      "encoding": {
        "y": {
          "field": "b",
          "type": "nominal",
          "sort": null,
          "axis": {
            "ticks": false,
            "domain": false,
            "title": null
          }
        },
        "size": {
          "field": "b",
          "type": "quantitative",
          "scale": {
            "type": "quantize"
          }
        },
        "color": {
          "field": "b",
          "type": "quantitative",
          "scale": {
            "type": "quantize",
            "zero": true
          },
          "legend": {
            "title": "Quantize"
          }
        }
      }
    },
    {
      "mark": "circle",
      "encoding": {
        "y": {
          "field": "b",
          "type": "nominal",
          "sort": null,
          "axis": {
            "ticks": false,
            "domain": false,
            "title": null
          }
        },
        "size": {
          "field": "b",
          "type": "quantitative",
          "scale": {
            "type": "quantile",
            "range": [80, 160, 240, 320, 400]
          }
        },
        "color": {
          "field": "b",
          "type": "quantitative",
          "scale": {
            "type": "quantile",
            "scheme": "magma"
          },
          "legend": {
            "format": "d",
            "title": "Quantile"
          }
        }
      }
    },
    {
      "mark": "circle",
      "encoding": {
        "y": {
          "field": "b",
          "type": "nominal",
          "sort": null,
          "axis": {
            "ticks": false,
            "domain": false,
            "title": null
          }
        },
        "size": {
          "field": "b",
          "type": "quantitative",
          "scale": {
            "type": "threshold",
            "domain": [30, 70],
            "range": [80, 200, 320]
          }
        },
        "color": {
          "field": "b",
          "type": "quantitative",
          "scale": {
            "type": "threshold",
            "domain": [30, 70],
            "scheme": "viridis"
          },
          "legend": {
            "title": "Threshold"
          }
        }
      }
    }
  ],
  "resolve": {
    "scale": {
      "color": "independent",
      "size": "independent"
    }
  }
}
....

== Vega Radar
[vega]
....
{
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "description": "A radar chart example, showing multiple dimensions in a radial layout.",
  "width": 400,
  "height": 400,
  "padding": 40,
  "autosize": {"type": "none", "contains": "padding"},

  "signals": [
    {"name": "radius", "update": "width / 2"}
  ],

  "data": [
    {
      "name": "table",
      "values": [
        {"key": "key-0", "value": 19, "category": 0},
        {"key": "key-1", "value": 22, "category": 0},
        {"key": "key-2", "value": 14, "category": 0},
        {"key": "key-3", "value": 38, "category": 0},
        {"key": "key-4", "value": 23, "category": 0},
        {"key": "key-5", "value": 5, "category": 0},
        {"key": "key-6", "value": 27, "category": 0},
        {"key": "key-0", "value": 13, "category": 1},
        {"key": "key-1", "value": 12, "category": 1},
        {"key": "key-2", "value": 42, "category": 1},
        {"key": "key-3", "value": 13, "category": 1},
        {"key": "key-4", "value": 6, "category": 1},
        {"key": "key-5", "value": 15, "category": 1},
        {"key": "key-6", "value": 8, "category": 1}
      ]
    },
    {
      "name": "keys",
      "source": "table",
      "transform": [
        {
          "type": "aggregate",
          "groupby": ["key"]
        }
      ]
    }
  ],

  "scales": [
    {
      "name": "angular",
      "type": "point",
      "range": {"signal": "[-PI, PI]"},
      "padding": 0.5,
      "domain": {"data": "table", "field": "key"}
    },
    {
      "name": "radial",
      "type": "linear",
      "range": {"signal": "[0, radius]"},
      "zero": true,
      "nice": false,
      "domain": {"data": "table", "field": "value"},
      "domainMin": 0
    },
    {
      "name": "color",
      "type": "ordinal",
      "domain": {"data": "table", "field": "category"},
      "range": {"scheme": "category10"}
    }
  ],

  "encode": {
    "enter": {
      "x": {"signal": "radius"},
      "y": {"signal": "radius"}
    }
  },

  "marks": [
    {
      "type": "group",
      "name": "categories",
      "zindex": 1,
      "from": {
        "facet": {"data": "table", "name": "facet", "groupby": ["category"]}
      },
      "marks": [
        {
          "type": "line",
          "name": "category-line",
          "from": {"data": "facet"},
          "encode": {
            "enter": {
              "interpolate": {"value": "linear-closed"},
              "x": {"signal": "scale('radial', datum.value) * cos(scale('angular', datum.key))"},
              "y": {"signal": "scale('radial', datum.value) * sin(scale('angular', datum.key))"},
              "stroke": {"scale": "color", "field": "category"},
              "strokeWidth": {"value": 1},
              "fill": {"scale": "color", "field": "category"},
              "fillOpacity": {"value": 0.1}
            }
          }
        },
        {
          "type": "text",
          "name": "value-text",
          "from": {"data": "category-line"},
          "encode": {
            "enter": {
              "x": {"signal": "datum.x"},
              "y": {"signal": "datum.y"},
              "text": {"signal": "datum.datum.value"},
              "align": {"value": "center"},
              "baseline": {"value": "middle"},
              "fill": {"value": "black"}
            }
          }
        }
      ]
    },
    {
      "type": "rule",
      "name": "radial-grid",
      "from": {"data": "keys"},
      "zindex": 0,
      "encode": {
        "enter": {
          "x": {"value": 0},
          "y": {"value": 0},
          "x2": {"signal": "radius * cos(scale('angular', datum.key))"},
          "y2": {"signal": "radius * sin(scale('angular', datum.key))"},
          "stroke": {"value": "lightgray"},
          "strokeWidth": {"value": 1}
        }
      }
    },
    {
      "type": "text",
      "name": "key-label",
      "from": {"data": "keys"},
      "zindex": 1,
      "encode": {
        "enter": {
          "x": {"signal": "(radius + 5) * cos(scale('angular', datum.key))"},
          "y": {"signal": "(radius + 5) * sin(scale('angular', datum.key))"},
          "text": {"field": "key"},
          "align": [
            {
              "test": "abs(scale('angular', datum.key)) > PI / 2",
              "value": "right"
            },
            {
              "value": "left"
            }
          ],
          "baseline": [
            {
              "test": "scale('angular', datum.key) > 0", "value": "top"
            },
            {
              "test": "scale('angular', datum.key) == 0", "value": "middle"
            },
            {
              "value": "bottom"
            }
          ],
          "fill": {"value": "black"},
          "fontWeight": {"value": "bold"}
        }
      }
    },
    {
      "type": "line",
      "name": "outer-line",
      "from": {"data": "radial-grid"},
      "encode": {
        "enter": {
          "interpolate": {"value": "linear-closed"},
          "x": {"field": "x2"},
          "y": {"field": "y2"},
          "stroke": {"value": "lightgray"},
          "strokeWidth": {"value": 1}
        }
      }
    }
  ]
}
....
